# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [68]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [69]:
# your code here
print(np.__version__)

1.22.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [70]:
# Method 1
a = np.random.random((2,3,5))
print(a)


[[[0.2724644  0.72402254 0.97737168 0.98002578 0.27115601]
  [0.63195157 0.44733513 0.97094701 0.0157507  0.76740727]
  [0.49773158 0.1908357  0.57764585 0.75440116 0.2685555 ]]

 [[0.11756498 0.29471762 0.88669245 0.1703867  0.19888085]
  [0.88243377 0.30593955 0.35898387 0.12546019 0.27757538]
  [0.17940743 0.32717881 0.12291612 0.06352393 0.77230648]]]


In [88]:
# Method 2
a1 = np.empty((2,3,5))
a1

array([[[0.2724644 , 0.72402254, 0.97737168, 0.98002578, 0.27115601],
        [0.63195157, 0.44733513, 0.97094701, 0.0157507 , 0.76740727],
        [0.49773158, 0.1908357 , 0.57764585, 0.75440116, 0.2685555 ]],

       [[0.11756498, 0.29471762, 0.88669245, 0.1703867 , 0.19888085],
        [0.88243377, 0.30593955, 0.35898387, 0.12546019, 0.27757538],
        [0.17940743, 0.32717881, 0.12291612, 0.06352393, 0.77230648]]])

In [89]:
# Method 3
copy_a = a.copy()
print(copy_a)

[[[0.2724644  0.72402254 0.97737168 0.98002578 0.27115601]
  [0.63195157 0.44733513 0.97094701 0.0157507  0.76740727]
  [0.49773158 0.1908357  0.57764585 0.75440116 0.2685555 ]]

 [[0.11756498 0.29471762 0.88669245 0.1703867  0.19888085]
  [0.88243377 0.30593955 0.35898387 0.12546019 0.27757538]
  [0.17940743 0.32717881 0.12291612 0.06352393 0.77230648]]]


#### 4. Print *a*.


In [90]:
# your code here
print(a)

[[[0.2724644  0.72402254 0.97737168 0.98002578 0.27115601]
  [0.63195157 0.44733513 0.97094701 0.0157507  0.76740727]
  [0.49773158 0.1908357  0.57764585 0.75440116 0.2685555 ]]

 [[0.11756498 0.29471762 0.88669245 0.1703867  0.19888085]
  [0.88243377 0.30593955 0.35898387 0.12546019 0.27757538]
  [0.17940743 0.32717881 0.12291612 0.06352393 0.77230648]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [91]:
# your code here
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [92]:
# your code here
print(b_ones_array)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [93]:
print(b.size)
print(a.size)

30
30


In [94]:
print(np.array_equal(a,b))

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [95]:
# your answer here
print(np.add(a,b))
#Se pueden sumar, siempre que las matrices tengan la misma estructura

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [96]:
# your code here
c = b.transpose()
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [100]:
# your code/answer here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [101]:
d = np.add(a, c)
print(d.shape)
print(d)

(2, 3, 5)
[[[1.2724644  1.72402254 1.97737168 1.98002578 1.27115601]
  [1.63195157 1.44733513 1.97094701 1.0157507  1.76740727]
  [1.49773158 1.1908357  1.57764585 1.75440116 1.2685555 ]]

 [[1.11756498 1.29471762 1.88669245 1.1703867  1.19888085]
  [1.88243377 1.30593955 1.35898387 1.12546019 1.27757538]
  [1.17940743 1.32717881 1.12291612 1.06352393 1.77230648]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [107]:
# your code/answer here
print(a)

print(d)

[[[0.2724644  0.72402254 0.97737168 0.98002578 0.27115601]
  [0.63195157 0.44733513 0.97094701 0.0157507  0.76740727]
  [0.49773158 0.1908357  0.57764585 0.75440116 0.2685555 ]]

 [[0.11756498 0.29471762 0.88669245 0.1703867  0.19888085]
  [0.88243377 0.30593955 0.35898387 0.12546019 0.27757538]
  [0.17940743 0.32717881 0.12291612 0.06352393 0.77230648]]]
[[[1.2724644  1.72402254 1.97737168 1.98002578 1.27115601]
  [1.63195157 1.44733513 1.97094701 1.0157507  1.76740727]
  [1.49773158 1.1908357  1.57764585 1.75440116 1.2685555 ]]

 [[1.11756498 1.29471762 1.88669245 1.1703867  1.19888085]
  [1.88243377 1.30593955 1.35898387 1.12546019 1.27757538]
  [1.17940743 1.32717881 1.12291612 1.06352393 1.77230648]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [108]:
# your code here
e = np.multiply(a, c)
e

array([[[0.2724644 , 0.72402254, 0.97737168, 0.98002578, 0.27115601],
        [0.63195157, 0.44733513, 0.97094701, 0.0157507 , 0.76740727],
        [0.49773158, 0.1908357 , 0.57764585, 0.75440116, 0.2685555 ]],

       [[0.11756498, 0.29471762, 0.88669245, 0.1703867 , 0.19888085],
        [0.88243377, 0.30593955, 0.35898387, 0.12546019, 0.27757538],
        [0.17940743, 0.32717881, 0.12291612, 0.06352393, 0.77230648]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [109]:
# your code/answer here
#Deberia de ser igual, ya que se ha multiplicado por uno(1)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [110]:
# your code here
d_min = d.min()
d_max = d.max()
d_mean = np.mean(d)
print(f'd_max is {d_max}')
print(f'd_min is {d_min}')
print(f'd_mean is {d_mean}')

d_max is 1.9800257830037964
d_min is 1.0157506988289786
d_mean is 1.4477190007031249


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [116]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[0.2724644  0.72402254 0.97737168 0.98002578 0.27115601]
  [0.63195157 0.44733513 0.97094701 0.0157507  0.76740727]
  [0.49773158 0.1908357  0.57764585 0.75440116 0.2685555 ]]

 [[0.11756498 0.29471762 0.88669245 0.1703867  0.19888085]
  [0.88243377 0.30593955 0.35898387 0.12546019 0.27757538]
  [0.17940743 0.32717881 0.12291612 0.06352393 0.77230648]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [117]:
# your code here
for value in d:
    if value.any() > d_min and value.any() < d_mean:
        value = 25
        value.append(f)

    if value.any() > d_mean and value.any() < d_max:
        value = 75
        value.append(f)

    if value.any() == d_mean:
        value = 50
        value.append(f)

    if value.any() == d_min:
        value = 0
        value.append(f)

    if value.any() == d_max:
        value = 100
        value.append(f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [120]:
# your code here
print(f)
print(d)

[[[0.2724644  0.72402254 0.97737168 0.98002578 0.27115601]
  [0.63195157 0.44733513 0.97094701 0.0157507  0.76740727]
  [0.49773158 0.1908357  0.57764585 0.75440116 0.2685555 ]]

 [[0.11756498 0.29471762 0.88669245 0.1703867  0.19888085]
  [0.88243377 0.30593955 0.35898387 0.12546019 0.27757538]
  [0.17940743 0.32717881 0.12291612 0.06352393 0.77230648]]]
[[[1.2724644  1.72402254 1.97737168 1.98002578 1.27115601]
  [1.63195157 1.44733513 1.97094701 1.0157507  1.76740727]
  [1.49773158 1.1908357  1.57764585 1.75440116 1.2685555 ]]

 [[1.11756498 1.29471762 1.88669245 1.1703867  1.19888085]
  [1.88243377 1.30593955 1.35898387 1.12546019 1.27757538]
  [1.17940743 1.32717881 1.12291612 1.06352393 1.77230648]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here